// <auto-generated />
using Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(DonutDbContext))]
    [Migration("20260622220930_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Application.Data.FuelItem", b =>
                {
                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<double>("SmeltCount")
                        .HasColumnType("REAL");

                    b.HasKey("ItemName");

                    b.ToTable("FuelItems");
                });

            modelBuilder.Entity("Application.Data.ManualItem", b =>
                {
                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemName");

                    b.ToTable("ManualItems");
                });

            modelBuilder.Entity("Application.Data.PriceOverride", b =>
                {
                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ItemName");

                    b.ToTable("PriceOverrides");
                });

            modelBuilder.Entity("Application.Data.PriceOverrideHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PriceOverrideHistories");
                });

            modelBuilder.Entity("Application.Data.PriceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("Application.Data.ProcessedTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.ToTable("ProcessedTransactions");
                });

            modelBuilder.Entity("Application.Data.StoredRecipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputQty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("OutputUseOverride")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
